spring:
  application:
    name: oslo-demo-biz-with-kotlin
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

server:
  port: 8082
